use crate::model::{CriticalThresholds, Panel, Parameter, RangeSpec};

pub fn find(id: &str) -> Option<&'static Parameter> {
    PARAMETERS.iter().find(|p| p.id == id)
}

const BLOOD_DIFFERENTIAL_URL: &str = "https://medlineplus.gov/lab-tests/blood-differential/";
const RBC_INDICES_URL: &str = "https://medlineplus.gov/lab-tests/red-blood-cell-rbc-indices/";
const CHOLESTEROL_URL: &str = "https://medlineplus.gov/lab-tests/cholesterol-levels/";
const IRON_TESTS_URL: &str = "https://medlineplus.gov/lab-tests/iron-tests/";
const PT_INR_URL: &str = "https://medlineplus.gov/ency/article/003652.htm";
const BILIRUBIN_URL: &str = "https://medlineplus.gov/lab-tests/bilirubin-blood-test/";

/// Adult reference ranges, SI units. General population ranges compiled from
/// standard clinical chemistry/hematology references. Local lab ranges may
/// differ slightly by analyzer/method and should be preferred when available.
/// `source_url` points to the MedlinePlus (NIH/National Library of Medicine)
/// page for that marker, used both as the cited source and as the in-app
/// "official guidance" link.
pub const PARAMETERS: &[Parameter] = &[
    // ---------------- CBC ----------------
    Parameter {
        id: "wbc",
        name: "White Blood Cell Count (WBC)",
        unit: "×10⁹/L",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 4.0, high: 11.0 },
        critical: Some(CriticalThresholds { low: Some(2.0), high: Some(30.0) }),
        description: "Total count of white blood cells, the immune system's primary defenders against infection.",
        high_meaning: "May be associated with bacterial infection, inflammation, tissue damage, stress response, corticosteroid use, or blood cancers such as leukemia.",
        low_meaning: "May be associated with viral infections, bone marrow suppression (e.g. chemotherapy, radiation), autoimmune disease, or severe/overwhelming infection outpacing production.",
        us_unit: "×10³/µL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/white-blood-count-wbc/",
        suggestion_high: Some("If related to acute illness or stress, rest, hydration, and allowing the body to recover are commonly recommended supportive measures (CDC)."),
        suggestion_low: None,
    },
    Parameter {
        id: "rbc",
        name: "Red Blood Cell Count (RBC)",
        unit: "×10¹²/L",
        panel: Panel::Cbc,
        range: RangeSpec::BySex { male: (4.5, 5.9), female: (4.0, 5.2) },
        critical: None,
        description: "Total count of red blood cells, which carry oxygen from the lungs to body tissues.",
        high_meaning: "May be associated with dehydration, chronic lung/heart disease causing low oxygen, smoking, living at high altitude, or polycythemia vera.",
        low_meaning: "May be associated with anemia from blood loss, iron/B12/folate deficiency, chronic kidney disease, or bone marrow disorders.",
        us_unit: "×10⁶/µL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/red-blood-cell-rbc-count/",
        suggestion_high: Some("Staying well hydrated and avoiding tobacco use are commonly associated with healthier red blood cell levels (CDC)."),
        suggestion_low: Some("Eating iron-rich foods (leafy greens, lean meat, legumes) alongside vitamin C to aid iron absorption is commonly recommended for mild, diet-related anemia (NIH)."),
    },
    Parameter {
        id: "hemoglobin",
        name: "Hemoglobin (Hgb)",
        unit: "g/L",
        panel: Panel::Cbc,
        range: RangeSpec::BySex { male: (135.0, 175.0), female: (120.0, 155.0) },
        critical: Some(CriticalThresholds { low: Some(70.0), high: Some(200.0) }),
        description: "The oxygen-carrying protein inside red blood cells; a core measure of anemia severity.",
        high_meaning: "May be associated with dehydration, smoking, chronic hypoxia (e.g. COPD, sleep apnea), or polycythemia vera. Very high levels raise clotting risk.",
        low_meaning: "Indicates anemia; may be associated with blood loss, iron/B12/folate deficiency, chronic disease, or bone marrow failure. Very low levels may require transfusion.",
        us_unit: "g/dL",
        si_to_us_factor: 0.1,
        source_url: "https://medlineplus.gov/lab-tests/hemoglobin-test/",
        suggestion_high: Some("Staying well hydrated and avoiding tobacco use are commonly associated with healthier hemoglobin levels (CDC)."),
        suggestion_low: Some("Eating iron-rich foods (leafy greens, lean meat, legumes) alongside vitamin C to aid iron absorption is commonly recommended for mild, diet-related anemia (NIH)."),
    },
    Parameter {
        id: "hematocrit",
        name: "Hematocrit (Hct)",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::BySex { male: (40.0, 54.0), female: (36.0, 48.0) },
        critical: None,
        description: "The percentage of blood volume made up of red blood cells; tracks closely with hemoglobin and RBC count.",
        high_meaning: "May be associated with dehydration, chronic hypoxia, smoking, or polycythemia vera.",
        low_meaning: "May be associated with anemia, recent blood loss, overhydration, or nutritional deficiency.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/hematocrit-test/",
        suggestion_high: Some("Staying well hydrated and avoiding tobacco use are commonly associated with healthier hematocrit levels (CDC)."),
        suggestion_low: Some("Eating iron-rich foods alongside vitamin C to aid absorption is commonly recommended for mild, diet-related anemia (NIH)."),
    },
    Parameter {
        id: "mcv",
        name: "Mean Corpuscular Volume (MCV)",
        unit: "fL",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 80.0, high: 100.0 },
        critical: None,
        description: "Average size of individual red blood cells; used to classify anemia as microcytic, normocytic, or macrocytic.",
        high_meaning: "May be associated with B12 or folate deficiency, alcohol use, liver disease, or hypothyroidism (macrocytic anemia).",
        low_meaning: "May be associated with iron deficiency or thalassemia (microcytic anemia).",
        us_unit: "fL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/mcv-mean-corpuscular-volume/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "mch",
        name: "Mean Corpuscular Hemoglobin (MCH)",
        unit: "pg",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 27.0, high: 33.0 },
        critical: None,
        description: "Average amount of hemoglobin per red blood cell.",
        high_meaning: "May be associated with macrocytic anemia (e.g. B12/folate deficiency).",
        low_meaning: "May be associated with iron deficiency anemia or thalassemia.",
        us_unit: "pg",
        si_to_us_factor: 1.0,
        source_url: RBC_INDICES_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "mchc",
        name: "Mean Corpuscular Hemoglobin Concentration (MCHC)",
        unit: "g/L",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 320.0, high: 360.0 },
        critical: None,
        description: "Concentration of hemoglobin within red blood cells, relative to cell volume.",
        high_meaning: "May be associated with hereditary spherocytosis or severe dehydration/hemoconcentration.",
        low_meaning: "May be associated with iron deficiency anemia or thalassemia.",
        us_unit: "g/dL",
        si_to_us_factor: 0.1,
        source_url: RBC_INDICES_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "rdw",
        name: "Red Cell Distribution Width (RDW)",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 11.5, high: 14.5 },
        critical: None,
        description: "Measures variation in red blood cell size; helps distinguish causes of anemia when combined with MCV.",
        high_meaning: "May be associated with iron/B12/folate deficiency, mixed anemia types, or recent blood transfusion.",
        low_meaning: "Not typically clinically significant on its own.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/rdw-red-cell-distribution-width/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "platelets",
        name: "Platelet Count",
        unit: "×10⁹/L",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 150.0, high: 400.0 },
        critical: Some(CriticalThresholds { low: Some(20.0), high: Some(1000.0) }),
        description: "Cell fragments essential for blood clotting.",
        high_meaning: "May be associated with inflammation, infection, iron deficiency, or a myeloproliferative disorder. Raises clotting risk at very high levels.",
        low_meaning: "May be associated with bone marrow suppression, autoimmune destruction, liver disease, or certain infections. Raises bleeding risk at very low levels.",
        us_unit: "×10³/µL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/platelet-tests/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "neutrophils",
        name: "Neutrophils",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 40.0, high: 75.0 },
        critical: None,
        description: "Most abundant white blood cell type; first responders against bacterial infection.",
        high_meaning: "May be associated with acute bacterial infection, inflammation, stress, or corticosteroid use.",
        low_meaning: "May be associated with viral infection, bone marrow suppression, or certain medications; increases infection risk when severe.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: BLOOD_DIFFERENTIAL_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "lymphocytes",
        name: "Lymphocytes",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 20.0, high: 45.0 },
        critical: None,
        description: "White blood cells responsible for viral defense and adaptive immunity (T cells, B cells).",
        high_meaning: "May be associated with viral infection, chronic lymphocytic leukemia, or certain chronic infections.",
        low_meaning: "May be associated with acute stress, corticosteroid use, HIV/AIDS, or autoimmune disease.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: BLOOD_DIFFERENTIAL_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "monocytes",
        name: "Monocytes",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 2.0, high: 10.0 },
        critical: None,
        description: "White blood cells that mature into macrophages, clearing pathogens and dead cells.",
        high_meaning: "May be associated with chronic infection, inflammatory disease, or recovery from acute infection.",
        low_meaning: "Not typically clinically significant on its own.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: BLOOD_DIFFERENTIAL_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "eosinophils",
        name: "Eosinophils",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 1.0, high: 6.0 },
        critical: None,
        description: "White blood cells involved in allergic response and defense against parasites.",
        high_meaning: "May be associated with allergies, asthma, parasitic infection, or certain drug reactions.",
        low_meaning: "Not typically clinically significant on its own.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: BLOOD_DIFFERENTIAL_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "basophils",
        name: "Basophils",
        unit: "%",
        panel: Panel::Cbc,
        range: RangeSpec::Fixed { low: 0.0, high: 2.0 },
        critical: None,
        description: "Least common white blood cell type, involved in allergic and inflammatory responses.",
        high_meaning: "May be associated with allergic reactions, chronic inflammation, or certain myeloproliferative disorders.",
        low_meaning: "Not typically clinically significant on its own.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: BLOOD_DIFFERENTIAL_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- CMP ----------------
    Parameter {
        id: "glucose",
        name: "Glucose (Fasting)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 3.9, high: 5.6 },
        critical: Some(CriticalThresholds { low: Some(2.8), high: Some(22.0) }),
        description: "Blood sugar level; central to diagnosing and monitoring diabetes.",
        high_meaning: "May be associated with diabetes, prediabetes, acute stress/illness, or corticosteroid use. Very high levels raise risk of DKA/HHS.",
        low_meaning: "May be associated with excess insulin/diabetes medication, prolonged fasting, alcohol use, or (rarely) an insulin-producing tumor. Severe hypoglycemia is a medical emergency.",
        us_unit: "mg/dL",
        si_to_us_factor: 18.0182,
        source_url: "https://medlineplus.gov/lab-tests/blood-glucose-test/",
        suggestion_high: Some("Regular physical activity, reducing added sugar and refined carbohydrate intake, and maintaining a healthy weight are commonly recommended for supporting healthy blood sugar levels (ADA/CDC)."),
        suggestion_low: Some("Eating regular, balanced meals and avoiding prolonged fasting can help prevent low blood sugar episodes (ADA)."),
    },
    Parameter {
        id: "urea",
        name: "Urea (BUN)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 2.5, high: 7.1 },
        critical: None,
        description: "Waste product of protein metabolism, filtered by the kidneys; reflects kidney function and hydration/protein intake.",
        high_meaning: "May be associated with dehydration, kidney impairment, high protein intake, or gastrointestinal bleeding.",
        low_meaning: "May be associated with overhydration, low protein intake, or severe liver disease.",
        us_unit: "mg/dL",
        si_to_us_factor: 2.8,
        source_url: "https://medlineplus.gov/lab-tests/bun-blood-urea-nitrogen/",
        suggestion_high: Some("Staying well hydrated is commonly recommended, since dehydration is a common contributor to an elevated BUN (NIH)."),
        suggestion_low: None,
    },
    Parameter {
        id: "creatinine",
        name: "Creatinine",
        unit: "µmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::BySex { male: (62.0, 106.0), female: (44.0, 80.0) },
        critical: None,
        description: "Waste product of muscle metabolism, filtered by the kidneys; the primary marker of kidney function.",
        high_meaning: "May be associated with acute or chronic kidney disease, dehydration, urinary obstruction, or high muscle mass.",
        low_meaning: "May be associated with low muscle mass, pregnancy, or malnutrition; rarely clinically significant alone.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.011312,
        source_url: "https://medlineplus.gov/lab-tests/creatinine-test/",
        suggestion_high: Some("Staying well hydrated and avoiding excessive protein or creatine-supplement intake are commonly suggested general measures (NIH)."),
        suggestion_low: None,
    },
    Parameter {
        id: "sodium",
        name: "Sodium (Na)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 135.0, high: 145.0 },
        critical: Some(CriticalThresholds { low: Some(120.0), high: Some(160.0) }),
        description: "Key electrolyte regulating fluid balance, nerve, and muscle function.",
        high_meaning: "May be associated with dehydration, excess salt intake, diabetes insipidus, or certain medications. Severe cases risk confusion/seizure.",
        low_meaning: "May be associated with overhydration, heart/liver/kidney failure, SIADH, or diuretic use. Severe cases risk confusion/seizure.",
        us_unit: "mEq/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/sodium-blood-test/",
        suggestion_high: Some("Reducing dietary sodium intake and staying well hydrated are commonly recommended (AHA)."),
        suggestion_low: None,
    },
    Parameter {
        id: "potassium",
        name: "Potassium (K)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 3.5, high: 5.0 },
        critical: Some(CriticalThresholds { low: Some(2.5), high: Some(6.5) }),
        description: "Key electrolyte critical for normal heart rhythm and muscle function.",
        high_meaning: "May be associated with kidney impairment, certain medications (e.g. ACE inhibitors, potassium-sparing diuretics), or tissue damage. Severe cases risk dangerous cardiac arrhythmia.",
        low_meaning: "May be associated with diuretic use, vomiting/diarrhea, or inadequate intake. Severe cases risk dangerous cardiac arrhythmia.",
        us_unit: "mEq/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/potassium-blood-test/",
        // Abnormal potassium carries meaningful cardiac risk and is often medication/kidney-driven;
        // deliberately no lifestyle suggestion here — this one should go to a clinician, not a diet tip.
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "chloride",
        name: "Chloride (Cl)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 98.0, high: 107.0 },
        critical: None,
        description: "Electrolyte that helps maintain fluid balance and acid-base status, usually tracking with sodium.",
        high_meaning: "May be associated with dehydration or metabolic acidosis.",
        low_meaning: "May be associated with vomiting, overhydration, or metabolic alkalosis.",
        us_unit: "mEq/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/chloride-blood-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "bicarbonate",
        name: "Bicarbonate (CO₂)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 22.0, high: 29.0 },
        critical: None,
        description: "Reflects the body's acid-base (pH) balance, largely controlled by the kidneys and lungs.",
        high_meaning: "May be associated with metabolic alkalosis or chronic respiratory acidosis (compensation).",
        low_meaning: "May be associated with metabolic acidosis, e.g. from kidney disease, diabetic ketoacidosis, or severe diarrhea.",
        us_unit: "mEq/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/carbon-dioxide-co2-in-blood/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "calcium",
        name: "Calcium (Total)",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 2.10, high: 2.55 },
        critical: Some(CriticalThresholds { low: Some(1.75), high: Some(3.25) }),
        description: "Essential mineral for bone health, nerve signaling, muscle contraction, and blood clotting.",
        high_meaning: "May be associated with hyperparathyroidism, certain cancers, excess vitamin D, or prolonged immobilization.",
        low_meaning: "May be associated with vitamin D deficiency, hypoparathyroidism, kidney disease, or low albumin.",
        us_unit: "mg/dL",
        si_to_us_factor: 4.008,
        source_url: "https://medlineplus.gov/lab-tests/calcium-blood-test/",
        // High calcium is often driven by parathyroid/malignancy causes best left to a clinician.
        suggestion_high: None,
        suggestion_low: Some("Adequate dietary calcium and vitamin D (from food, sunlight, or supplementation as advised by a clinician) are commonly recommended (NIH)."),
    },
    Parameter {
        id: "total_protein",
        name: "Total Protein",
        unit: "g/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 60.0, high: 80.0 },
        critical: None,
        description: "Combined measure of all blood proteins, mainly albumin and globulins; reflects nutrition, liver, and kidney status.",
        high_meaning: "May be associated with chronic inflammation, dehydration, or certain blood disorders (e.g. multiple myeloma).",
        low_meaning: "May be associated with malnutrition, liver disease, kidney protein loss, or malabsorption.",
        us_unit: "g/dL",
        si_to_us_factor: 0.1,
        source_url: "https://medlineplus.gov/lab-tests/total-protein-and-albumin-globulin-a-g-ratio/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "albumin",
        name: "Albumin",
        unit: "g/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 35.0, high: 50.0 },
        critical: None,
        description: "Main protein made by the liver; maintains fluid balance and transports substances in the blood.",
        high_meaning: "Usually reflects dehydration rather than a disease process.",
        low_meaning: "May be associated with liver disease, malnutrition, chronic inflammation, or kidney/GI protein loss.",
        us_unit: "g/dL",
        si_to_us_factor: 0.1,
        source_url: "https://medlineplus.gov/lab-tests/albumin-blood-test/",
        suggestion_high: None,
        suggestion_low: Some("Adequate dietary protein intake is commonly recommended to support healthy albumin levels (NIH)."),
    },
    Parameter {
        id: "total_bilirubin",
        name: "Total Bilirubin",
        unit: "µmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 3.4, high: 20.5 },
        critical: None,
        description: "Breakdown product of red blood cells, processed by the liver; elevated levels cause jaundice.",
        high_meaning: "May be associated with liver disease, bile duct obstruction, or increased red blood cell breakdown (hemolysis).",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.05848,
        source_url: BILIRUBIN_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "alp",
        name: "Alkaline Phosphatase (ALP)",
        unit: "U/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 30.0, high: 120.0 },
        critical: None,
        description: "Enzyme found in liver and bone; used to assess liver/bile duct disease and bone turnover.",
        high_meaning: "May be associated with bile duct obstruction, liver disease, bone disorders, or (normally) active bone growth in adolescents.",
        low_meaning: "May be associated with malnutrition, hypothyroidism, or certain genetic conditions.",
        us_unit: "U/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/alkaline-phosphatase/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "ast",
        name: "Aspartate Aminotransferase (AST)",
        unit: "U/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 5.0, high: 40.0 },
        critical: None,
        description: "Liver enzyme also found in heart and muscle tissue; elevated with cell damage in those organs.",
        high_meaning: "May be associated with liver injury (e.g. alcohol, fatty liver, hepatitis), muscle injury, or heart attack.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "U/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/ast-test/",
        suggestion_high: Some("Limiting alcohol intake and maintaining a healthy weight are commonly associated with supporting healthy liver enzyme levels (CDC/NIH)."),
        suggestion_low: None,
    },
    Parameter {
        id: "alt",
        name: "Alanine Aminotransferase (ALT)",
        unit: "U/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 7.0, high: 56.0 },
        critical: None,
        description: "Liver enzyme more specific to the liver than AST; a key marker of liver cell damage.",
        high_meaning: "May be associated with fatty liver disease, viral hepatitis, alcohol use, or medication-induced liver injury.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "U/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/alt-blood-test/",
        suggestion_high: Some("Limiting alcohol intake and maintaining a healthy weight are commonly associated with supporting healthy liver enzyme levels (CDC/NIH)."),
        suggestion_low: None,
    },
    // ---------------- Lipid Panel ----------------
    Parameter {
        id: "total_cholesterol",
        name: "Total Cholesterol",
        unit: "mmol/L",
        panel: Panel::Lipid,
        range: RangeSpec::Fixed { low: 0.0, high: 5.2 },
        critical: None,
        description: "Combined measure of all cholesterol carried in the blood (LDL + HDL + a fraction of triglycerides).",
        high_meaning: "May be associated with increased cardiovascular disease risk; influenced by diet, genetics, weight, and activity level.",
        low_meaning: "Not typically a clinical concern; very low levels occasionally relate to liver disease, malnutrition, or hyperthyroidism.",
        us_unit: "mg/dL",
        si_to_us_factor: 38.67,
        source_url: CHOLESTEROL_URL,
        suggestion_high: Some("Reducing saturated fat intake, increasing physical activity, and maintaining a healthy weight are commonly recommended to help lower cholesterol (AHA)."),
        suggestion_low: None,
    },
    Parameter {
        id: "ldl",
        name: "LDL Cholesterol",
        unit: "mmol/L",
        panel: Panel::Lipid,
        range: RangeSpec::Fixed { low: 0.0, high: 3.4 },
        critical: None,
        description: "\"Bad\" cholesterol; carries cholesterol into artery walls and is a key driver of atherosclerosis.",
        high_meaning: "Associated with increased risk of atherosclerosis, heart attack, and stroke; target thresholds are lower for those with existing cardiovascular disease or diabetes.",
        low_meaning: "Not typically a clinical concern.",
        us_unit: "mg/dL",
        si_to_us_factor: 38.67,
        source_url: CHOLESTEROL_URL,
        suggestion_high: Some("Reducing saturated fat intake, increasing physical activity, and maintaining a healthy weight are commonly recommended to help lower LDL cholesterol (AHA)."),
        suggestion_low: None,
    },
    Parameter {
        id: "hdl",
        name: "HDL Cholesterol",
        unit: "mmol/L",
        panel: Panel::Lipid,
        range: RangeSpec::BySex { male: (1.0, 2.6), female: (1.3, 2.6) },
        critical: None,
        description: "\"Good\" cholesterol; helps remove excess cholesterol from the bloodstream. Higher is generally protective.",
        high_meaning: "Generally protective against cardiovascular disease; very high levels are uncommon and not typically concerning.",
        low_meaning: "Associated with increased cardiovascular disease risk; may relate to smoking, obesity, sedentary lifestyle, or type 2 diabetes.",
        us_unit: "mg/dL",
        si_to_us_factor: 38.67,
        source_url: CHOLESTEROL_URL,
        suggestion_high: None,
        suggestion_low: Some("Regular aerobic exercise and avoiding tobacco use are commonly associated with higher HDL levels (AHA)."),
    },
    Parameter {
        id: "triglycerides",
        name: "Triglycerides",
        unit: "mmol/L",
        panel: Panel::Lipid,
        range: RangeSpec::Fixed { low: 0.0, high: 1.7 },
        critical: Some(CriticalThresholds { low: None, high: Some(11.3) }),
        description: "A type of fat in the blood, mainly from dietary fat and excess calories; a cardiovascular risk factor.",
        high_meaning: "May be associated with obesity, poorly controlled diabetes, excess alcohol/sugar intake, or genetic lipid disorders. Very high levels raise risk of pancreatitis.",
        low_meaning: "Not typically a clinical concern.",
        us_unit: "mg/dL",
        si_to_us_factor: 88.57,
        source_url: "https://medlineplus.gov/lab-tests/triglycerides-test/",
        suggestion_high: Some("Limiting added sugars, alcohol, and refined carbohydrates, along with regular physical activity, are commonly recommended to help lower triglycerides (AHA)."),
        suggestion_low: None,
    },
    // ---------------- Thyroid Panel ----------------
    Parameter {
        id: "tsh",
        name: "Thyroid-Stimulating Hormone (TSH)",
        unit: "mIU/L",
        panel: Panel::Thyroid,
        range: RangeSpec::Fixed { low: 0.4, high: 4.0 },
        critical: None,
        description: "Pituitary hormone that signals the thyroid to make more or less thyroid hormone; the usual first-line thyroid function test.",
        high_meaning: "May be associated with an underactive thyroid (hypothyroidism) \u{2014} fatigue, weight gain, cold intolerance, or depression.",
        low_meaning: "May be associated with an overactive thyroid (hyperthyroidism) \u{2014} weight loss, anxiety, rapid heart rate, or heat intolerance.",
        us_unit: "mIU/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/tsh-thyroid-stimulating-hormone-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "free_t4",
        name: "Free T4 (Thyroxine)",
        unit: "pmol/L",
        panel: Panel::Thyroid,
        range: RangeSpec::Fixed { low: 10.0, high: 20.0 },
        critical: None,
        description: "The active, unbound form of thyroxine circulating in the blood; used with TSH to assess thyroid function.",
        high_meaning: "May be associated with an overactive thyroid (hyperthyroidism).",
        low_meaning: "May be associated with an underactive thyroid (hypothyroidism).",
        us_unit: "ng/dL",
        si_to_us_factor: 0.0777,
        source_url: "https://medlineplus.gov/lab-tests/thyroxine-t4-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "free_t3",
        name: "Free T3 (Triiodothyronine)",
        unit: "pmol/L",
        panel: Panel::Thyroid,
        range: RangeSpec::Fixed { low: 3.5, high: 6.5 },
        critical: None,
        description: "The active, unbound form of triiodothyronine, the thyroid hormone with the strongest direct metabolic effect.",
        high_meaning: "May be associated with an overactive thyroid (hyperthyroidism).",
        low_meaning: "May be associated with an underactive thyroid (hypothyroidism) or severe non-thyroidal illness.",
        us_unit: "pg/mL",
        si_to_us_factor: 0.651,
        source_url: "https://medlineplus.gov/lab-tests/triiodothyronine-t3-tests/",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Iron Studies ----------------
    Parameter {
        id: "ferritin",
        name: "Ferritin",
        unit: "\u{b5}g/L",
        panel: Panel::IronStudies,
        range: RangeSpec::BySex { male: (20.0, 250.0), female: (10.0, 120.0) },
        critical: None,
        description: "Protein that stores iron; the best overall indicator of the body's total iron stores.",
        high_meaning: "May be associated with inflammation, liver disease, excess alcohol use, or iron overload (hemochromatosis). Ferritin also rises non-specifically with any inflammation, which can mask an underlying iron deficiency.",
        low_meaning: "Indicates depleted iron stores (iron deficiency), often before anemia becomes apparent on a CBC.",
        us_unit: "ng/mL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/ferritin-blood-test/",
        suggestion_high: None,
        suggestion_low: Some("Eating iron-rich foods (leafy greens, lean meat, legumes) alongside vitamin C to aid absorption is commonly recommended for mild, diet-related iron deficiency (NIH)."),
    },
    Parameter {
        id: "serum_iron",
        name: "Serum Iron",
        unit: "\u{b5}mol/L",
        panel: Panel::IronStudies,
        range: RangeSpec::Fixed { low: 10.7, high: 32.2 },
        critical: None,
        description: "The amount of iron currently circulating in the blood, bound to transferrin.",
        high_meaning: "May be associated with hemochromatosis, iron poisoning, or liver damage.",
        low_meaning: "May be associated with iron deficiency, chronic disease, or recent blood loss.",
        us_unit: "\u{b5}g/dL",
        si_to_us_factor: 5.585,
        source_url: IRON_TESTS_URL,
        suggestion_high: None,
        suggestion_low: Some("Eating iron-rich foods (leafy greens, lean meat, legumes) alongside vitamin C to aid absorption is commonly recommended for mild, diet-related iron deficiency (NIH)."),
    },
    Parameter {
        id: "tibc",
        name: "Total Iron-Binding Capacity (TIBC)",
        unit: "\u{b5}mol/L",
        panel: Panel::IronStudies,
        range: RangeSpec::Fixed { low: 45.0, high: 73.0 },
        critical: None,
        description: "Measures the blood's overall capacity to bind and transport iron via transferrin; rises when iron stores are low.",
        high_meaning: "May be associated with iron deficiency.",
        low_meaning: "May be associated with hemochromatosis, chronic disease, or malnutrition.",
        us_unit: "\u{b5}g/dL",
        si_to_us_factor: 5.585,
        source_url: IRON_TESTS_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "transferrin_saturation",
        name: "Transferrin Saturation",
        unit: "%",
        panel: Panel::IronStudies,
        range: RangeSpec::BySex { male: (20.0, 50.0), female: (15.0, 45.0) },
        critical: None,
        description: "The percentage of transferrin (the iron-transport protein) that is currently carrying iron; combines serum iron and TIBC into one measure.",
        high_meaning: "May be associated with hemochromatosis or iron overload.",
        low_meaning: "May be associated with iron deficiency.",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: IRON_TESTS_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Vitamin Panel ----------------
    Parameter {
        id: "vitamin_d",
        name: "Vitamin D (25-Hydroxy)",
        unit: "nmol/L",
        panel: Panel::Vitamins,
        range: RangeSpec::Fixed { low: 50.0, high: 125.0 },
        critical: Some(CriticalThresholds { low: Some(25.0), high: Some(375.0) }),
        description: "The main circulating form of vitamin D; reflects both dietary intake and skin production from sunlight exposure.",
        high_meaning: "Uncommon outside of excessive supplementation; may raise blood calcium levels at very high levels.",
        low_meaning: "Indicates vitamin D deficiency; may be associated with bone pain, muscle weakness, or increased fracture risk.",
        us_unit: "ng/mL",
        si_to_us_factor: 0.4,
        source_url: "https://medlineplus.gov/lab-tests/vitamin-d-test/",
        suggestion_high: None,
        suggestion_low: Some("Sensible sun exposure, vitamin D-rich foods, and supplementation as advised by a clinician are commonly recommended (NIH)."),
    },
    Parameter {
        id: "vitamin_b12",
        name: "Vitamin B12",
        unit: "pmol/L",
        panel: Panel::Vitamins,
        range: RangeSpec::Fixed { low: 219.0, high: 773.0 },
        critical: None,
        description: "Essential vitamin for red blood cell formation and nerve function.",
        high_meaning: "Uncommon; may be associated with liver disease or certain blood disorders. Not typically a clinical concern on its own.",
        low_meaning: "May be associated with B12 deficiency \u{2014} anemia, numbness/tingling, weakness, or balance problems. More common with vegan diets, pernicious anemia, or after weight-loss surgery.",
        us_unit: "pg/mL",
        si_to_us_factor: 1.364,
        source_url: "https://medlineplus.gov/ency/article/003705.htm",
        suggestion_high: None,
        suggestion_low: Some("Dietary B12 (meat, dairy, eggs, fortified foods) or supplementation as advised by a clinician is commonly recommended, especially for vegan/vegetarian diets (NIH)."),
    },
    Parameter {
        id: "folate",
        name: "Folate (Folic Acid)",
        unit: "nmol/L",
        panel: Panel::Vitamins,
        range: RangeSpec::Fixed { low: 6.12, high: 38.52 },
        critical: None,
        description: "B vitamin essential for red blood cell formation and DNA synthesis; often tested alongside vitamin B12.",
        high_meaning: "Not typically clinically significant.",
        low_meaning: "May be associated with folate deficiency \u{2014} anemia, and (in pregnancy) increased risk of neural tube defects.",
        us_unit: "ng/mL",
        si_to_us_factor: 0.441,
        source_url: "https://medlineplus.gov/ency/article/003686.htm",
        suggestion_high: None,
        suggestion_low: Some("Folate-rich foods (leafy greens, legumes, fortified grains) or supplementation as advised by a clinician are commonly recommended, particularly for those who are pregnant or planning pregnancy (NIH)."),
    },
    // ---------------- Inflammatory Markers ----------------
    Parameter {
        id: "crp",
        name: "C-Reactive Protein (CRP)",
        unit: "mg/L",
        panel: Panel::Inflammatory,
        range: RangeSpec::Fixed { low: 0.0, high: 10.0 },
        critical: None,
        description: "General marker of inflammation, produced by the liver in response to infection, injury, or chronic inflammatory disease.",
        high_meaning: "May be associated with infection, injury, chronic inflammatory conditions (e.g. rheumatoid arthritis, inflammatory bowel disease), or increased cardiovascular risk. Does not indicate the location or cause of inflammation on its own.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.1,
        source_url: "https://medlineplus.gov/lab-tests/c-reactive-protein-crp-test/",
        suggestion_high: Some("Regular physical activity, a diet lower in processed foods, and not smoking are commonly associated with lower baseline inflammation markers (AHA)."),
        suggestion_low: None,
    },
    Parameter {
        id: "esr",
        name: "Erythrocyte Sedimentation Rate (ESR)",
        unit: "mm/hr",
        panel: Panel::Inflammatory,
        range: RangeSpec::BySex { male: (0.0, 15.0), female: (0.0, 20.0) },
        critical: None,
        description: "Measures how quickly red blood cells settle in a tube over one hour; a general, non-specific marker of inflammation. Also rises somewhat with age.",
        high_meaning: "May be associated with infection, autoimmune disease, other inflammatory conditions, or certain cancers.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mm/hr",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/ency/article/003638.htm",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Coagulation Panel ----------------
    Parameter {
        id: "pt",
        name: "Prothrombin Time (PT)",
        unit: "sec",
        panel: Panel::Coagulation,
        range: RangeSpec::Fixed { low: 11.0, high: 13.5 },
        critical: None,
        description: "Measures how long it takes blood to clot via the extrinsic clotting pathway; used to assess bleeding risk and (via INR) monitor warfarin therapy.",
        high_meaning: "May be associated with liver disease, vitamin K deficiency, warfarin use, or clotting factor deficiencies. Raises bleeding risk.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "sec",
        si_to_us_factor: 1.0,
        source_url: PT_INR_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "inr",
        name: "International Normalized Ratio (INR)",
        unit: "ratio",
        panel: Panel::Coagulation,
        range: RangeSpec::Fixed { low: 0.8, high: 1.1 },
        critical: None,
        description: "A standardized version of PT that allows clotting results to be compared across labs; used mainly to monitor warfarin (blood-thinner) therapy, where a higher target range is intentional.",
        high_meaning: "May be associated with over-anticoagulation (e.g. warfarin), liver disease, or vitamin K deficiency. Raises bleeding risk. Note: those taking warfarin are intentionally targeted to a higher INR (often 2.0–3.0) — this general reference range is for someone not on blood thinners.",
        low_meaning: "May indicate under-anticoagulation in someone taking warfarin; otherwise not typically clinically significant.",
        us_unit: "ratio",
        si_to_us_factor: 1.0,
        source_url: PT_INR_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "aptt",
        name: "Activated Partial Thromboplastin Time (aPTT)",
        unit: "sec",
        panel: Panel::Coagulation,
        range: RangeSpec::Fixed { low: 25.0, high: 35.0 },
        critical: None,
        description: "Measures how long it takes blood to clot via the intrinsic clotting pathway; used to assess bleeding disorders and monitor heparin therapy.",
        high_meaning: "May be associated with hemophilia, von Willebrand disease, liver disease, heparin use, or clotting factor deficiencies. Raises bleeding risk.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "sec",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/ency/article/003653.htm",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Cardiac Markers ----------------
    Parameter {
        id: "troponin",
        name: "Troponin",
        unit: "\u{b5}g/L",
        panel: Panel::Cardiac,
        range: RangeSpec::Fixed { low: 0.0, high: 0.04 },
        critical: None,
        description: "Protein released into the blood when heart muscle is damaged; the primary blood marker used to diagnose a heart attack. Reference range and cutoff vary significantly by assay/manufacturer — confirm against your lab's own reported cutoff, not this general value.",
        high_meaning: "May indicate heart muscle injury, most commonly a heart attack; can also rise with severe heart failure, myocarditis, kidney failure, or extreme physical exertion. A significantly elevated troponin, especially with chest pain, is a medical emergency — seek immediate care.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "ng/mL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/troponin-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "nt_probnp",
        name: "NT-proBNP",
        unit: "pmol/L",
        panel: Panel::Cardiac,
        range: RangeSpec::Fixed { low: 0.0, high: 14.8 },
        critical: None,
        description: "Hormone released by the heart in response to stretching or strain; used to help diagnose or rule out heart failure. Reference range varies significantly by age, sex, and assay/manufacturer — confirm against your lab's own cutoff.",
        high_meaning: "May be associated with heart failure; also commonly rises with age, kidney disease, and other cardiac conditions.",
        low_meaning: "A low result makes heart failure unlikely as the cause of symptoms.",
        us_unit: "pg/mL",
        si_to_us_factor: 8.457,
        source_url: "https://medlineplus.gov/lab-tests/natriuretic-peptide-tests-bnp-nt-probnp/",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Autoimmune Markers ----------------
    Parameter {
        id: "ana",
        name: "Antinuclear Antibody (ANA)",
        unit: "titer",
        panel: Panel::Autoimmune,
        range: RangeSpec::Fixed { low: 0.0, high: 40.0 },
        critical: None,
        description: "Screens for antibodies that target the body's own cell nuclei; used to help evaluate for autoimmune conditions such as lupus. Represented here as the titer denominator only (a result reported as \"1:80\" is entered as 80) — real reports also include a staining pattern (e.g. speckled, homogeneous) not captured by this app, and the positive/negative cutoff varies by lab.",
        high_meaning: "A positive/elevated ANA titer may be associated with autoimmune conditions such as lupus, rheumatoid arthritis, scleroderma, or Sjögren's syndrome — but a positive result alone does not diagnose any specific disease, and a low-level positive is fairly common in people without autoimmune disease.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "titer",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/ana-antinuclear-antibody-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "rheumatoid_factor",
        name: "Rheumatoid Factor (RF)",
        unit: "IU/mL",
        panel: Panel::Autoimmune,
        range: RangeSpec::Fixed { low: 0.0, high: 14.0 },
        critical: None,
        description: "Antibody sometimes present in autoimmune conditions, most notably rheumatoid arthritis; often tested alongside anti-CCP antibodies.",
        high_meaning: "May be associated with rheumatoid arthritis or other autoimmune/inflammatory conditions, but can also be positive in some healthy people, particularly with age, or with chronic infections.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "IU/mL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/rheumatoid-factor-rf-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- Hormones ----------------
    Parameter {
        id: "cortisol",
        name: "Cortisol (AM)",
        unit: "nmol/L",
        panel: Panel::Hormones,
        range: RangeSpec::Fixed { low: 140.0, high: 690.0 },
        critical: None,
        description: "Hormone made by the adrenal glands that helps regulate stress response, metabolism, and blood pressure; levels normally peak in the morning and fall by afternoon. This range reflects a morning (AM) sample.",
        high_meaning: "May be associated with Cushing's syndrome, chronic stress, or certain medications (e.g. corticosteroids).",
        low_meaning: "May be associated with adrenal insufficiency (Addison's disease) or pituitary disorders.",
        us_unit: "\u{b5}g/dL",
        si_to_us_factor: 0.03625,
        source_url: "https://medlineplus.gov/lab-tests/cortisol-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "testosterone",
        name: "Testosterone (Total)",
        unit: "nmol/L",
        panel: Panel::Hormones,
        range: RangeSpec::BySex { male: (10.0, 35.0), female: (0.5, 2.4) },
        critical: None,
        description: "Primary male sex hormone, also present in smaller amounts in women; affects muscle mass, bone density, libido, and mood.",
        high_meaning: "May be associated with certain tumors, PCOS (in women), or anabolic steroid use.",
        low_meaning: "In men, may be associated with hypogonadism, aging, obesity, or pituitary disorders; in women, low levels are less commonly a clinical concern. May contribute to fatigue, low libido, or reduced muscle mass.",
        us_unit: "ng/dL",
        si_to_us_factor: 28.85,
        source_url: "https://medlineplus.gov/lab-tests/testosterone-levels-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "psa",
        name: "Prostate-Specific Antigen (PSA)",
        unit: "\u{b5}g/L",
        panel: Panel::Hormones,
        range: RangeSpec::Fixed { low: 0.0, high: 4.0 },
        critical: None,
        description: "Protein made by the prostate gland; used mainly to screen for and monitor prostate cancer. Applies to men only (no prostate in women).",
        high_meaning: "May be associated with prostate cancer, benign prostatic hyperplasia (enlarged prostate), or prostatitis (inflammation/infection). An elevated PSA alone does not diagnose cancer — further testing is needed.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "ng/mL",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/prostate-specific-antigen-psa-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "fsh",
        name: "Follicle-Stimulating Hormone (FSH)",
        unit: "IU/L",
        panel: Panel::Hormones,
        range: RangeSpec::Fixed { low: 1.0, high: 12.0 },
        critical: None,
        description: "Pituitary hormone that regulates reproductive function; drives sperm production in men and egg development in women. Levels vary substantially by sex, menstrual cycle phase, and menopause status — this is a general adult range only; postmenopausal women normally have much higher levels.",
        high_meaning: "May be associated with primary gonadal failure, menopause, or (in men) testicular failure.",
        low_meaning: "May be associated with pituitary or hypothalamic dysfunction.",
        us_unit: "IU/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/follicle-stimulating-hormone-fsh-levels-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "lh",
        name: "Luteinizing Hormone (LH)",
        unit: "IU/L",
        panel: Panel::Hormones,
        range: RangeSpec::Fixed { low: 1.0, high: 9.0 },
        critical: None,
        description: "Pituitary hormone that triggers ovulation in women and supports testosterone production in men. Levels vary substantially by sex, menstrual cycle phase, and menopause status — this is a general adult range only; postmenopausal women normally have much higher levels.",
        high_meaning: "May be associated with primary gonadal failure, menopause, or PCOS.",
        low_meaning: "May be associated with pituitary or hypothalamic dysfunction.",
        us_unit: "IU/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/luteinizing-hormone-lh-levels-test/",
        suggestion_high: None,
        suggestion_low: None,
    },
    // ---------------- CMP additions ----------------
    Parameter {
        id: "hba1c",
        name: "Hemoglobin A1c (HbA1c)",
        unit: "%",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 0.0, high: 5.7 },
        critical: None,
        description: "Reflects average blood sugar control over the past 2–3 months, based on the percentage of hemoglobin coated with glucose; central to diagnosing and monitoring diabetes.",
        high_meaning: "5.7–6.4% suggests prediabetes; 6.5% or higher suggests diabetes. May also be associated with poorly controlled existing diabetes.",
        low_meaning: "Not typically a clinical concern; low levels occasionally relate to conditions affecting red blood cell turnover (e.g. hemolytic anemia).",
        us_unit: "%",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/hemoglobin-a1c-hba1c-test/",
        suggestion_high: Some("Regular physical activity, reducing added sugar and refined carbohydrate intake, and maintaining a healthy weight are commonly recommended for supporting healthy blood sugar levels (ADA/CDC)."),
        suggestion_low: None,
    },
    Parameter {
        id: "egfr",
        name: "Estimated GFR (eGFR)",
        unit: "mL/min/1.73m\u{b2}",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 90.0, high: 200.0 },
        critical: Some(CriticalThresholds { low: Some(15.0), high: None }),
        description: "Estimated Glomerular Filtration Rate; the standard overall measure of kidney function, calculated from creatinine plus age and sex — usually already calculated and printed on the lab report rather than measured directly.",
        high_meaning: "Not a clinically meaningful finding — eGFR has no clinical upper concern.",
        low_meaning: "May indicate reduced kidney function; used to stage chronic kidney disease severity. Very low levels may indicate kidney failure.",
        us_unit: "mL/min/1.73m\u{b2}",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/glomerular-filtration-rate-gfr-test/",
        suggestion_high: None,
        suggestion_low: Some("Managing blood pressure and blood sugar, staying well hydrated, and avoiding unnecessary NSAID use are commonly recommended to help protect kidney function (NIH)."),
    },
    Parameter {
        id: "uric_acid",
        name: "Uric Acid",
        unit: "\u{b5}mol/L",
        panel: Panel::Cmp,
        range: RangeSpec::BySex { male: (238.0, 512.0), female: (178.0, 422.0) },
        critical: None,
        description: "Waste product from the breakdown of purines; builds up in the blood when produced in excess or cleared inefficiently by the kidneys.",
        high_meaning: "May be associated with gout, kidney disease, or high purine intake (red meat, alcohol, sugary drinks).",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.0168,
        source_url: "https://medlineplus.gov/ency/article/003476.htm",
        suggestion_high: Some("Limiting alcohol, red meat, and sugary drinks, along with staying well hydrated, are commonly recommended to help lower uric acid (NIH)."),
        suggestion_low: None,
    },
    Parameter {
        id: "magnesium",
        name: "Magnesium",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 0.70, high: 0.90 },
        critical: None,
        description: "Essential mineral involved in muscle and nerve function, blood sugar control, and bone health.",
        high_meaning: "May be associated with kidney impairment or excessive magnesium supplement/antacid use.",
        low_meaning: "May be associated with poor dietary intake, alcohol use, diarrhea, or certain diuretics; can cause muscle cramps or irregular heart rhythm.",
        us_unit: "mg/dL",
        si_to_us_factor: 2.43,
        source_url: "https://medlineplus.gov/lab-tests/magnesium-blood-test/",
        suggestion_high: None,
        suggestion_low: Some("Magnesium-rich foods (leafy greens, nuts, whole grains) are commonly recommended (NIH)."),
    },
    Parameter {
        id: "phosphate",
        name: "Phosphate",
        unit: "mmol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 0.9, high: 1.5 },
        critical: None,
        description: "Mineral that works closely with calcium for bone health and is involved in energy storage and use throughout the body.",
        high_meaning: "May be associated with kidney disease, excess vitamin D, or a low-calcium state.",
        low_meaning: "May be associated with malnutrition, alcohol use disorder, or certain hormonal conditions.",
        us_unit: "mg/dL",
        si_to_us_factor: 3.1,
        source_url: "https://medlineplus.gov/lab-tests/phosphate-in-blood/",
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "ggt",
        name: "Gamma-Glutamyl Transferase (GGT)",
        unit: "U/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 9.0, high: 48.0 },
        critical: None,
        description: "Liver enzyme especially sensitive to alcohol use and bile duct issues; often used alongside ALP to determine whether an elevated ALP originates from the liver or bone.",
        high_meaning: "May be associated with alcohol use, fatty liver disease, bile duct obstruction, or certain medications.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "U/L",
        si_to_us_factor: 1.0,
        source_url: "https://medlineplus.gov/lab-tests/gamma-glutamyl-transferase-ggt-test/",
        suggestion_high: Some("Limiting alcohol intake is commonly associated with lower GGT levels (NIH)."),
        suggestion_low: None,
    },
    Parameter {
        id: "direct_bilirubin",
        name: "Direct (Conjugated) Bilirubin",
        unit: "\u{b5}mol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 0.0, high: 5.1 },
        critical: None,
        description: "The water-soluble, \"conjugated\" form of bilirubin processed by the liver; a rise here specifically points toward liver or bile duct problems rather than red blood cell breakdown.",
        high_meaning: "May be associated with liver disease or bile duct obstruction.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.05848,
        source_url: BILIRUBIN_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
    Parameter {
        id: "indirect_bilirubin",
        name: "Indirect (Unconjugated) Bilirubin",
        unit: "\u{b5}mol/L",
        panel: Panel::Cmp,
        range: RangeSpec::Fixed { low: 3.4, high: 15.4 },
        critical: None,
        description: "The \"unconjugated\" form of bilirubin not yet processed by the liver, calculated as Total minus Direct bilirubin; a rise here specifically points toward increased red blood cell breakdown (hemolysis) rather than a liver/bile duct problem.",
        high_meaning: "May be associated with hemolysis (increased red blood cell breakdown), certain inherited conditions (e.g. Gilbert syndrome), or newborn jaundice.",
        low_meaning: "Not typically clinically significant.",
        us_unit: "mg/dL",
        si_to_us_factor: 0.05848,
        source_url: BILIRUBIN_URL,
        suggestion_high: None,
        suggestion_low: None,
    },
];
